FROM python:3.6-slim-buster
LABEL maintainer="Aleks Volochnev" \
      maintainer_email="a.volochnev@gmail.com"
ENV FLASK_APP=app.py \
    FLASK_ENV=development
ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app.py .
